FE_10 add axios pacgake, created axios istance and file env, get one film f…rom api and display in page
leszczynskidawid/YtClone pull request #8
Opened 2023-04-05 08:10 UTC by leszczynskidawid

add axios pacgake, created axios istance and file env, get one film f…rom api and display in page

2023-04-06 19:18 UTC, leszczynskidawid commented on src/Constants/apiClinetMethodsName.js
> +  GET: "get",
dopisać metody

2023-04-24 08:46 UTC, baumanmilosz commented on src/Components/SearchInput/index.js
> +// import { apiClient } from "../../Helpers/apiClient";
?

2023-04-24 08:46 UTC, baumanmilosz commented on src/Components/VideoCard/index.js
> +            alt="green iguana"
?

2023-04-24 08:49 UTC, baumanmilosz commented on src/Constants/Endpoints/getEnpoins.js
> +  GET_VIDEO_BY_ID: `/videos?part=snippet%2CcontentDetails%2Cstatistics&id=wr3VmbZdVA4`,
człon do `...mostPopular` z endpointu api mozna wyodrebnic do zmiennej skoro się powtarza

2023-04-24 08:49 UTC, baumanmilosz commented on src/Constants/Endpoints/getEnpoins.js
> +    "playlists?part=snippet%2CcontentDetails&channelId=UC_x5XG1OV2P6uZZ5FSM9Ttw&maxResults=25",
`channelId` jest zahardcodowany, dlaczego?

2023-04-24 08:49 UTC, baumanmilosz commented on src/Constants/Endpoints/getEnpoins.js
> +  GET_VIDEO_25_RESULTS_WITH_WORD_KEY_PERFECT_ASS:
`PERFECT_ASS`?

2023-04-24 08:50 UTC, baumanmilosz commented on src/Helpers/apiClient.js
> +  // headers: { "Access-Control-Allow-Origin": "*" },
?

2023-04-24 08:51 UTC, baumanmilosz commented on src/Helpers/handleExceptionsErrors.js
> +  switch (status) {
proponuje zrobic jakis toast/alert na FE w przypadku błedu, sprawdz jak jest na yt

2023-04-24 08:54 UTC, baumanmilosz requested changes

2023-04-24 08:54 UTC, baumanmilosz commented on src/Hooks/useApi.js
> +        endpoints + `&key=${REACT_APP_API_KEY}`
key mozna zawrzec wyrzej w hierarchi, a nie bezposrednio w hooku do pobierania danych

2023-04-24 08:54 UTC, baumanmilosz commented on src/Hooks/useApi.js
> +      const response = await apiClient.get(
storzyles enumy z metodami HTTP, a ich nie uzywasz

2023-10-26 19:20 UTC, merged